Test check error

diff --git a/.github/workflows/update-dockerhub-description.yml b/.github/workflows/update-dockerhub-description.yml
--- a/.github/workflows/update-dockerhub-description.yml
+++ b/.github/workflows/update-dockerhub-description.yml
@@ -35,10 +35,14 @@ jobs:
         if: env.update_needed == 'true'
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
+          DOCKERHUB_REPO: $${{ vars.DOCKERHUB_REPO }}
           DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
         run: |
-          curl -X PATCH "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}/" \
+          response=$(curl -w "%{http_code}" -X PATCH "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}/" \
           -H "Authorization: JWT ${DOCKERHUB_PASSWORD}" \
           -H "Content-Type: application/json" \
-          -d "{\"full_description\": $(jq -Rs . < README.md)}"
+          -d "{\"full_description\": $(jq -Rs . < README.md)}")
+          if [ "$response" -ne 200 ]; then
+            echo "Error: Request failed with HTTP status $response" >&2
+            exit 1
+          fi
